apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portshift-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: portshift-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: portshift-operator
  namespace: {{ .Release.Namespace }}